/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary": "#2C6E59",
        "primary-light": "#0b5542",
        "primary-container": "#2c6e59",
        "on-primary": "#ffffff",
        "on-primary-container": "#ffffff",
        "secondary": "#A2E037",
        "secondary-container": "#b6f64c",
        "on-secondary": "#1A1D1F",
        "on-secondary-container": "#1a1d1f",
        "tertiary": "#00563a",
        "tertiary-container": "#00714e",
        "tertiary-fixed-dim": "#42dfa3",
        "background": "#f7f9f5",
        "surface": "#f7f9f5",
        "surface-bright": "#f8faf6",
        "surface-dim": "#d8dbd7",
        "surface-container": "#eceeeb",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#f2f4f1",
        "surface-container-high": "#e6e9e5",
        "surface-container-highest": "#e1e3e0",
        "surface-variant": "#e1e3e0",
        "on-surface": "#191c1b",
        "on-surface-variant": "#3f4944",
        "on-background": "#191c1b",
        "outline": "#707974",
        "outline-variant": "#d0d5d0",
        "inverse-surface": "#2e312f",
        "inverse-on-surface": "#eff1ee",
        "inverse-primary": "#92d4ba",
        "error": "#ba1a1a",
        "error-container": "#ffdad6",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "charcoal": "#1A1D1F",
        "cool-grey": "#808A93",
        "forest-green": "#2c6e59",
        "lime-green": "#a2e037",
        "deep-forest": "#2c6e59",
        "lime": "#A2E037",
        "mint-green": "#00C288",
        "accent-lime": "#A2E037",
        "positive": "#00C288",
        "negative-bg": "#FBEBEB",
      },
      borderRadius: {
        DEFAULT: "0.5rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      spacing: {
        "stack-sm": "8px",
        "stack-md": "16px",
        "stack-lg": "32px",
        "unit": "4px",
        "container-padding": "24px",
        "gutter-grid": "16px",
        "gutter": "20px",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        mono: ["'JetBrains Mono'", "monospace"],
        "display-lg": ["'Plus Jakarta Sans'"],
        "headline-lg": ["'Plus Jakarta Sans'"],
        "headline-md": ["'Plus Jakarta Sans'"],
        "body-lg": ["'Plus Jakarta Sans'"],
        "body-md": ["'Plus Jakarta Sans'"],
        "title-lg": ["'Plus Jakarta Sans'"],
        "title-md": ["'Plus Jakarta Sans'"],
        "label-md": ["'Plus Jakarta Sans'"],
        "label-sm": ["'JetBrains Mono'"],
        "data-tabular": ["'JetBrains Mono'"],
      },
      fontSize: {
        "display-lg": ["48px", { lineHeight: "56px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "700" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "title-lg": ["20px", { lineHeight: "28px", fontWeight: "700" }],
        "title-md": ["16px", { lineHeight: "24px", fontWeight: "600" }],
        "label-md": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "label-sm": ["10px", { lineHeight: "12px", letterSpacing: "0.05em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "500" }],
        "data-tabular": ["14px", { lineHeight: "20px", fontWeight: "400" }],
      },
      backgroundImage: {
        "gradient-primary": "linear-gradient(135deg, #2C6E59 0%, #1a4a3a 100%)",
        "gradient-lime": "linear-gradient(135deg, #A2E037 0%, #7bc42a 100%)",
        "gradient-surface": "linear-gradient(180deg, #ffffff 0%, #f2f4f1 100%)",
        "gradient-radial": "radial-gradient(ellipse at top, rgba(44, 110, 89, 0.08) 0%, transparent 70%)",
        "gradient-hero": "radial-gradient(ellipse 80% 60% at 50% -10%, rgba(44,110,89,0.12) 0%, transparent 70%)",
      },
      boxShadow: {
        "card": "0 1px 3px rgba(0,0,0,0.04), 0 4px 12px rgba(0,0,0,0.04)",
        "card-hover": "0 4px 8px rgba(0,0,0,0.06), 0 12px 32px rgba(44, 110, 89, 0.10)",
        "glow-primary": "0 0 24px rgba(44, 110, 89, 0.20), 0 0 48px rgba(44, 110, 89, 0.08)",
        "glow-lime": "0 0 24px rgba(162, 224, 55, 0.25)",
        "inner-sm": "inset 0 1px 2px rgba(0,0,0,0.04)",
      },
      keyframes: {
        "fade-in": {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        "fade-in-up": {
          "0%": { opacity: "0", transform: "translateY(20px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "fade-in-down": {
          "0%": { opacity: "0", transform: "translateY(-12px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "slide-in-left": {
          "0%": { opacity: "0", transform: "translateX(-20px)" },
          "100%": { opacity: "1", transform: "translateX(0)" },
        },
        "scale-in": {
          "0%": { opacity: "0", transform: "scale(0.96)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-6px)" },
        },
        "pulse-soft": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
        "marquee": {
          "0%": { transform: "translateX(0)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "loading-bar": {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        "spin-slow": {
          "0%": { transform: "rotate(0deg)" },
          "100%": { transform: "rotate(360deg)" },
        },
        "shimmer": {
          "0%": { backgroundPosition: "-200% 0" },
          "100%": { backgroundPosition: "200% 0" },
        },
        "bar-grow": {
          "0%": { transform: "scaleY(0)", transformOrigin: "bottom" },
          "100%": { transform: "scaleY(1)", transformOrigin: "bottom" },
        },
        "ring-fill": {
          "0%": { strokeDashoffset: "440" },
          "100%": { strokeDashoffset: "105" },
        },
        "blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in-up": "fade-in-up 0.6s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "fade-in-down": "fade-in-down 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "slide-in-left": "slide-in-left 0.5s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "scale-in": "scale-in 0.4s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "float": "float 4s ease-in-out infinite",
        "pulse-soft": "pulse-soft 2.5s ease-in-out infinite",
        "marquee": "marquee 22s linear infinite",
        "loading": "loading-bar 1.5s ease-in-out infinite",
        "spin-slow": "spin-slow 8s linear infinite",
        "shimmer": "shimmer 2s linear infinite",
        "bar-grow": "bar-grow 0.8s cubic-bezier(0.16, 1, 0.3, 1) forwards",
        "blink": "blink 1.2s ease-in-out infinite",
      },
      transitionTimingFunction: {
        "spring": "cubic-bezier(0.16, 1, 0.3, 1)",
        "smooth": "cubic-bezier(0.4, 0, 0.2, 1)",
      },
    },
  },
  plugins: [],
};
